optimizer: FedAvg
learning_rate: 0.1
beta_1: 0.95
beta_2: 0.99
tau: 0.000000001
weight_clients: same
weight_list: []
rounds: 200
pretrain_rounds: 1
paper_faithful_pretrain: false
dht_collection_rounds: 0
participation: selection
client_info: groupweights_triplets
selection_method: random
fedpns_alpha: 2
fedpns_beta: 0.7
update_static_info_rounds: 0
num_active_clients: 9
multiclass: true
afed_generator: false
fairfed_beta: 0.1
